//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CLIENTE
    {
       
    
        public int CLIID { get; set; }
        public string CLINOMBRES { get; set; }
        public string CLIAPELLIDOS { get; set; }
        public string CLIDIRECCION { get; set; }
        public string CLICELULAR { get; set; }
        public string CLICORREO { get; set; }
    
      
    }
}
