//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
       
    
        public int EMPID { get; set; }
        public string EMPNOMBRES { get; set; }
        public string EMPAPELLIDOS { get; set; }
        public System.DateTime EMPFECHANACIMIENTO { get; set; }
        public string EMPCELULAR { get; set; }
        public string EMPCORREO { get; set; }
        public string EMPDIRECCION { get; set; }
    
      
    }
}
